import { useState } from "react";

import ICSGenerator from '../components/Calendar/ICSGenerator';
import EventForm from '../components/Calendar/EventForm';
// type eventDetailsProps = {
//   title: string,
//   startDate: Date,
//   endDate: Date,
//   location: string,
// }
// import { getAnswer } from '../langchain';

function IcsEvent() {

  
  // const [count, setCount] = useState(0);
  const [generatedICS, setGeneratedICS] = useState("");

  // Set the generated ICS data using setGeneratedICS
  // const generateICS = (eventDetails: eventDetailsProps, icsDetail: string) => {  
  const generateICS = (icsDetail: string) => {  
    // Use eventDetails to generate ICS data
    // const { title, startDate, endDate, location } = eventDetails;

    // For simplicity, let's use a simple example
    //     const icsData = `BEGIN:VCALENDAR
    // VERSION:2.0
    // BEGIN:VEVENT
    // SUMMARY:${eventDetails.title}
    // DTSTART:${eventDetails.startDate
    //       .toISOString()
    //       .replace(/[-:]/g, "")
    //       .replace(/\.\d{3}/, "")}Z
    // DTEND:${eventDetails.endDate
    //       .toISOString()
    //       .replace(/[-:]/g, "")
    //       .replace(/\.\d{3}/, "")}Z
    // LOCATION:${eventDetails.location}
    // DESCRIPTION:Generated by React ICS Generator Event
    // END:VEVENT
    // END:VCALENDAR`;
//     const icsData = `BEGIN:VCALENDAR
// VERSION:2.0
// BEGIN:VEVENT
// SUMMARY:${title}
// DTSTART:${startDate
//         .toISOString()
//         .replace(/[-:]/g, "")
//         .replace(/\.\d{3}/, "")}Z
// DTEND:${endDate
//         .toISOString()
//         .replace(/[-:]/g, "")
//         .replace(/\.\d{3}/, "")}Z
// LOCATION:${location}
// DESCRIPTION:Generated by React ICS Generator Event
// END:VEVENT
// END:VCALENDAR`;

    //     const icsExample = `BEGIN:VCALENDAR
    // VERSION:2.0
    // PRODID:-//Bevy Labs//Bevy//
    // METHOD:REQUEST
    // BEGIN:VEVENT
    // SUMMARY:Introduction au Salesforce Commerce Cloud
    // DTSTART;VALUE=DATE-TIME:20240217T133000Z
    // DTEND;VALUE=DATE-TIME:20240217T170000Z
    // DTSTAMP;VALUE=DATE-TIME:20240130T205651Z
    // UID:salesforce/44484/Event/Bevy
    // SEQUENCE:1706648211
    // ATTENDEE;CN="Abdelilah AKHMIM";PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT;RSVP
    //  =TRUE:MAILTO:akhmim.abdelilah@gmail.com
    // DESCRIPTION:Plongez dans l'univers de Salesforce Commerce Cloud et explore
    //  z ses produits essentiels tels que B2C, B2B, D2C et OMS. Découvrez les 
    //  fondamentaux, astuces et bonnes pratiques de cette plateforme puissante p
    //  our optimiser les opérations e-commerce de vos clients.
    // LOCATION:Commons Zerktouni, 179, Angle des Boulevards de Londres et de l
    //  a Résistance, Casablanca, 20250
    // PRIORITY:5
    // STATUS:CONFIRMED
    // END:VEVENT
    // END:VCALENDAR`;
    const icsData = icsDetail;

    setGeneratedICS(icsData);
  };
  return (
    <>
      <h1>React ICS Generator Event</h1>
      <div>

      </div>

      <div>
        <EventForm generateICS={generateICS} />
        {/* {generatedICS && <ICSGenerator eventDetails={generatedICS} />} */}
        {generatedICS && <ICSGenerator icsData={generatedICS} />}
      </div>
    </>
  );
}

export default IcsEvent;
